services:
  db:
    container_name: homework_3
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - homework_3:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB' ]
      interval: 5s
      retries: 5
      timeout: 10s
    networks:
      - homework_3

  app:
    container_name: homework_3_app
    build: .
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c 'python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --preload'
    networks:
      - homework_3

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - homework_3

volumes:
  homework_3:

networks:
  homework_3:
