# Generated by Django 5.1.7 on 2025-03-31 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("breeds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Имя собаки")),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст собаки")),
                ("gender", models.CharField(choices=[("male", "Мальчик"), ("female", "Девочка")], max_length=10)),
                ("color", models.CharField(max_length=100, verbose_name="Цвет собаки")),
                (
                    "favorite_food",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Любимое еда собаки"),
                ),
                (
                    "favorite_toy",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Любимая игрушка собаки"),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dogs",
                        to="breeds.breed",
                        verbose_name="Порода собаки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Собака",
                "verbose_name_plural": "Собаки",
                "ordering": ["name"],
            },
        ),
    ]
