# Generated by Django 5.1.7 on 2025-03-31 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название породы")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "Маленький"),
                            ("small", "Малый"),
                            ("medium", "Средний"),
                            ("large", "Большой"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "friendliness",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Дружелюбие",
                    ),
                ),
                (
                    "trainability",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Обучаемость",
                    ),
                ),
                (
                    "shedding_amount",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Объем шерсти",
                    ),
                ),
                (
                    "exercise_needs",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Требования к физической активности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Порода",
                "verbose_name_plural": "Породы",
                "ordering": ["name"],
            },
        ),
    ]
